In [4]:
#1.Debug the given code
import pandas as pd

data = {'Feature1': ['10', '20', 'Thirty'],  # 'Thirty' is not a valid number
        'Feature2': [5.5, 6.7, 8.9]}

df = pd.DataFrame(data)
df['Feature1'] = df['Feature1'].astype(int)  # Error: Cannot convert 'Thirty' to int

print(df)



   Feature1  Feature2
0        10       5.5
1        20       6.7
2        30       8.9


In [7]:
#ANS:
import pandas as pd
data = {'Feature1': ['10', '20', 'Thirty'], 
        'Feature2': [5.5, 6.7, 8.9]} 
df = pd.DataFrame(data)
df['Feature1'] = pd.to_numeric(df['Feature1'], errors='coerce')
#errores=coerce means ,convert any invaild or unconvertible value into Nan value instead of raising  error.
#to_numeric function is used to convert data in to  numeric value
print(df)


   Feature1  Feature2
0      10.0       5.5
1      20.0       6.7
2       NaN       8.9


In [10]:
#2.
import pandas as pd

data = {'A': [1, 2, None],  # Missing value
        'B': [4, None, 6]}  # Missing value

df = pd.DataFrame(data)
mean_value = df.mean()
df.fillna(mean_value) # Error: fillna() does not modify in place

print(df)


     A    B
0  1.0  4.0
1  2.0  NaN
2  NaN  6.0


In [11]:
#ANS:
data = {'A': [1, 2, None],  
        'B': [4, None, 6]}

df = pd.DataFrame(data)
mean_value = df.mean()
df.fillna(mean_value,inplace=True) 
#inplace=True means make the changes directly in existing dataframe
print(df)


     A    B
0  1.0  4.0
1  2.0  5.0
2  1.5  6.0


In [ ]:
#3.from sklearn.linear_model import LinearRegression
import numpy as np
X = np.array([1, 2, 3, 4, 5])# Error: X should be 2D
y = np.array([2, 4, 6, 8, 10])

model = LinearRegression()
model.fit(X, y)


In [6]:
#ANS:
from sklearn.linear_model import LinearRegression
import numpy as np
X = np.array([1, 2, 3, 4, 5])
X=X.reshape(-1,1)
#reshape(-1,1) convert 1D into 2D array.(-1,1) represent no of rows & Columns 
y = np.array([2, 4, 6, 8, 10])
model = LinearRegression()
model.fit(X, y)
print(model.predict([[8]]))  # Predict for new value



[16.]


In [5]:
#4.
from sklearn.preprocessing import StandardScaler
import numpy as np

data = np.array([10, 20, 30, 40, 50])  # Error: Should be 2D
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)

print(scaled_data)


[[-1. -1. -1.]
 [ 1.  1.  1.]]


In [7]:
#ANS:
from sklearn.preprocessing import StandardScaler
import numpy as np
data = np.array([10, 20, 30, 40, 50]) 
#data = np.array([[10], [20], [30],[30], [40], [50]])  
data=data.reshape(-1,1)#Reshape the data
scaler = StandardScaler()
scaled_data = scaler.fit_transform(data)
print(scaled_data)


[[-1.41421356]
 [-0.70710678]
 [ 0.        ]
 [ 0.70710678]
 [ 1.41421356]]


In [ ]:
#5.
from sklearn.linear_model import LogisticRegression

X = [[1, 2], [3, 4], [5, 6]]
y = ['yes', 'no', 'yes']  # Error: Labels should be numeric

model = LogisticRegression()
model.fit(X, y)


In [9]:
#ANS:
from sklearn.linear_model import LogisticRegression
from sklearn.preprocessing import LabelEncoder
X = [[1, 2], [3, 4], [5, 6]]
y = ['yes', 'no', 'yes']
encoder=LabelEncoder()#It convert categorial data into numercial
new_y=encoder.fit_transform(y)
model = LogisticRegression()
model.fit(X, new_y)
print(model.predict([[4, 5]]))

[1]


In [ ]:
#6
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

df = pd.DataFrame({'Category': ['A', 'B', 'C', 'A']})

encoder = OneHotEncoder()
encoded = encoder.fit_transform(df['Category'])  # Error: Data should be reshaped
print(encoded)


In [14]:
#ANS:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
df = pd.DataFrame({'Category': ['A', 'B', 'C', 'A']})
encoder = OneHotEncoder()
encoded = encoder.fit_transform(df[["Category"]]) # Convert to 2D
print(encoded.toarray())#toarray() convert sprase matrix(it store only non zero values so sane lot of memory) into normal Numpy array


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]


In [ ]:
#7
from sklearn.model_selection import train_test_split

X = [[1, 2], [3, 4], [5, 6], [7, 8]]
y = [0, 1, 0]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


In [29]:
ANS:
from sklearn.model_selection import train_test_split

X = [[1, 2], [3, 4], [5, 6], [7, 8]]
y = [0, 1, 0,0]

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)


In [ ]:
#8.from sklearn.linear_model import LogisticRegression

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = ["yes", "no", "yes"]  # Error: LogisticRegression expects numerical labels

model = LogisticRegression()
model.fit(X_train, y_train)


In [17]:
#ANS:
from sklearn.linear_model import LogisticRegression

X_train = [[1, 2], [3, 4], [5, 6]]
y_train = [0, 1, 0]  # Convert labels to numeric

model = LogisticRegression()
model.fit(X_train, y_train)
print(model.predict([[2, 3]]))


[0]


In [ ]:
#9
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression

# Creating a dataset with missing values
X_train = np.array([[1, 2], [3, np.nan], [5, 6]])
y_train = np.array([10, 20, 30])

model = LinearRegression()
model.fit(X_train, y_train)  


In [4]:
#ANS:
import numpy as np
import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.impute import SimpleImputer

# Creating a dataset with missing values
X_train = np.array([[1, 2], [3, np.nan], [5, 6]])
y_train = np.array([10, 20, 30])
# Handling missing values by replacing NaN with the column mean
#SimpleImputer fills the missingvalues automatically using meam,median
impute=SimpleImputer(strategy="mean")
x_train_impute=impute.fit_transform(X_train)
# Train the model
model = LinearRegression()
model.fit(x_train_impute,y_train)
#Make prediction
result=model.predict([[3,4]])
print("Predicted Output:",result)


Predicted Output: [20.]


In [ ]:
#10.
from sklearn.tree import DecisionTreeClassifier
X_train = [[1, 2], [3, 4], [5, 6]]
y_train =[["spam"], ["ham"],["spam"]]  # Error: String labels not allowed

model = DecisionTreeClassifier()
model.fit(X_train, y_train)


In [9]:
#ANS:
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import OneHotEncoder
import numpy as np
X_train = [[1, 2], [3, 4], [5, 6]]
y_train =[["spam"], ["ham"],["spam"]]  
#Convert categorial data into numercial
onehot=OneHotEncoder() 
y_train_one=onehot.fit_transform(y_train)
model = DecisionTreeClassifier()
y_trainarr=y_train_one.toarray()
#Train the model
model.fit(X_train,y_trainarr)
print(model.predict([[1, 2]]))


[[0. 1.]]


In [ ]:
#11.
from sklearn.svm import SVC

X_train = [[1, 100], [2, 200], [3, 300]]
y_train = [0, 1, 0]

model = SVC()
model.fit(X_train, y_train)
print(model.predict([[1, 150]]))  # Unreliable output due to large-scale difference


In [10]:
#ANS:
from sklearn.svm import SVC
from sklearn.preprocessing import  StandardScaler
scaler = StandardScaler()
#The training input have different range so it will give poorly predictions.To overcome these problems we use preprocessing concepts (ie)standardization 
X_train = [[1, 100], [2, 200], [3, 300]]
x_train=scaler.fit_transform(X_train)
y_train = [0, 1, 0]

model = SVC()
model.fit(x_train, y_train)
X_test_scaled = scaler.transform([[1, 150]])  # More reliable output
print(model.predict(X_test_scaled))


[0]
